FirstTry/Controllers/StorageUsingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FirstTry;

namespace FirstTry.Controllers
{
    public class StorageUsingController : Controller
    {
        private polyclinicEntities db = new polyclinicEntities();

        // GET: StorageUsing
        [Authorize(Roles = "director, manager")]
        public ActionResult Index(string sortOrder, string[] SearchStrings)
        {
            var storage_using = db.storage_using.Include(s => s.doctors).Include(s => s.storage).ToList();

            ViewBag.countSortParm = sortOrder == "count" ? "count_desc" : "count";
            ViewBag.dateSortParm = sortOrder == "date" ? "date_desc" : "date";
            ViewBag.docFIOSortParm = sortOrder == "docFIO" ? "docFIO_desc" : "docFIO";
            ViewBag.stItem_nameSortParm = sortOrder == "stItem_name" ? "stItem_name_desc" : "stItem_name";

            ViewData["sortOrder"] = sortOrder;

            if (SearchStrings != null && SearchStrings.Length == 1)
            {
                SearchStrings = SearchStrings[0].Split('%');
            }
            ViewBag.SearchStrings = SearchStrings;

            storage_using = SortData(sortOrder, storage_using);

            if (SearchStrings != null && SearchStrings.Length == 4)
                storage_using = SearchData(SearchStrings, storage_using);

            return View(storage_using);
        }

        public List<storage_using> SearchData(string[] SearchStrings, List<storage_using> storage_using)
        {
            if (!string.IsNullOrEmpty(SearchStrings[0]))
            {
                storage_using = storage_using.Where(s => s.count.ToString().Contains(SearchStrings[0])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[1]))
            {
                storage_using = storage_using.Where(s => s.date.ToString().Contains(SearchStrings[1])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[2]))
            {
                storage_using = storage_using.Where(s => s.doctors.FIO.ToString().Contains(SearchStrings[2])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[3]))
            {
                storage_using = storage_using.Where(s => s.storage.item_name.Contains(SearchStrings[3])).ToList();
            }

            return storage_using;
        }

        public List<storage_using> SortData(string sortOrder, List<storage_using> storage_using)
        {
            switch (sortOrder)
            {
                case "count":
                    storage_using = storage_using.OrderBy(s => s.count).ToList();
                    break;
                case "count_desc":
                    storage_using = storage_using.OrderByDescending(s => s.count).ToList();
                    break;
                case "date":
                    storage_using = storage_using.OrderBy(s => s.date).ToList();
                    break;
                case "date_desc":
                    storage_using = storage_using.OrderByDescending(s => s.date).ToList();
                    break;
                case "docFIO":
                    storage_using = storage_using.OrderBy(s => s.doctors.FIO).ToList();
                    break;
                case "docFIO_desc":
                    storage_using = storage_using.OrderByDescending(s => s.doctors.FIO).ToList();
                    break;
                case "stItem_name":
                    storage_using = storage_using.OrderBy(s => s.storage.item_name).ToList();
                    break;
                case "stItem_name_desc":
                    storage_using = storage_using.OrderByDescending(s => s.storage.item_name).ToList();
                    break;
            }

            return storage_using;
        }

        // GET: StorageUsing/Details/5
        [Authorize(Roles = "manager")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            storage_using storage_using = db.storage_using.Find(id);
            if (storage_using == null)
            {
                return HttpNotFound();
            }
            return View(storage_using);
        }

        // GET: StorageUsing/Create
        [Authorize(Roles = "manager")]
        public ActionResult Create()
        {
            ViewBag.doctor_id = new SelectList(db.doctors.Where((it) => it.date_end_work == null), "id", "FIO");
            ViewBag.item_id = new SelectList(db.storage, "item_id", "item_name").Where((it) => db.storage.Find(int.Parse(it.Value)).count > 0 && db.storage.Find(int.Parse(it.Value)).is_written_off != true).ToList();

            

            storage_using storage_using = new storage_using();
            storage_using.date = DateTime.Now;

            return View(storage_using);
        }

        // POST: StorageUsing/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "manager")]
        public ActionResult Create([Bind(Include = "id,doctor_id,item_id,count,date")] storage_using storage_using)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.storage_using.Add(storage_using);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    if (ex.InnerException != null && ex.InnerException.InnerException != null)
                    {
                        var mess = ex.InnerException.InnerException.Message;
                        ViewData["error"] = mess.Substring(0, mess.Length > 65 ? mess.Length - 65 : mess.Length);
                    }
                }
            }

            ViewBag.doctor_id = new SelectList(db.doctors, "id", "FIO", storage_using.doctor_id);
            ViewBag.item_id = new SelectList(db.storage, "item_id", "item_name", storage_using.item_id);
            return View(storage_using);
        }

        // GET: StorageUsing/Edit/5
        [Authorize(Roles = "manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            storage_using storage_using = db.storage_using.Find(id);
            if (storage_using == null)
            {
                return HttpNotFound();
            }
            ViewBag.doctor_id = new SelectList(db.doctors, "id", "FIO", storage_using.doctor_id);
            ViewBag.item_id = new SelectList(db.storage, "item_id", "item_name", storage_using.item_id);
            return View(storage_using);
        }

        // POST: StorageUsing/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "manager")]
        public ActionResult Edit([Bind(Include = "id,doctor_id,item_id,count,date")] storage_using storage_using)
        {
            if (ModelState.IsValid)
            {
                db.Entry(storage_using).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.doctor_id = new SelectList(db.doctors, "id", "FIO", storage_using.doctor_id);
            ViewBag.item_id = new SelectList(db.storage, "item_id", "item_name", storage_using.item_id);
            return View(storage_using);
        }

        // GET: StorageUsing/Delete/5
        [Authorize(Roles = "manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            storage_using storage_using = db.storage_using.Find(id);
            if (storage_using == null)
            {
                return HttpNotFound();
            }
            return View(storage_using);
        }

        // POST: StorageUsing/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "manager")]
        public ActionResult DeleteConfirmed(int id)
        {
            storage_using storage_using = db.storage_using.Find(id);
            db.storage_using.Remove(storage_using);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FirstTry/Views/StorageUsing/Create.cshtml
@model FirstTry.storage_using

@{
    ViewBag.Title = "Create";
}

<div class="alert-danger">
    @ViewData["error"]
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Створення</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.doctor_id, "doctor_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("doctor_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.doctor_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.item_id, "item_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("item_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.item_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FirstTry/Views/StorageUsing/Delete.cshtml
@model FirstTry.storage_using

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Видалення</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doctors.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctors.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.storage.item_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.storage.item_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FirstTry/Views/StorageUsing/Details.cshtml
@model FirstTry.storage_using

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Перегляд</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doctors.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctors.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.storage.item_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.storage.item_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FirstTry/Views/StorageUsing/Edit.cshtml
@model FirstTry.storage_using

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Редагування</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.doctor_id, "doctor_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("doctor_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.doctor_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.item_id, "item_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("item_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.item_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FirstTry/Views/StorageUsing/Index.cshtml
@model IEnumerable<FirstTry.storage_using>

@{
    ViewBag.Title = "Index";
}

@{ string ShowButton(string up, string down)
    {
        if (ViewData["sortOrder"] != null)
        {

            if (ViewData["sortOrder"].ToString() == up)
            {
                return HttpUtility.HtmlEncode("↑");
            }
            else if (ViewData["sortOrder"].ToString() == down)
            {
                return HttpUtility.HtmlEncode("↓");
            }
        }
        return "";
    }
}

@{ string GetSearchString(int index)
    {
        if (ViewBag.SearchStrings != null)
        {
            return ViewBag.SearchStrings[index];
        }
        return string.Empty;
    }
}

@{ string GetAgregateSearchString()
    {
        if (ViewBag.SearchStrings != null)
        {
            return (ViewBag.SearchStrings as string[]).Aggregate((sum, next) => sum + '%' + next);
        }
        return string.Empty;
    }
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("", "StorageUsing", FormMethod.Get, new { id = "searchform" }))
{

}

<input type="text" name="sortOrder" form="searchform" value="@ViewData["sortOrder"]" class="hidden" />

<table class="table">
    <tr>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(0)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(1)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(2)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(3)" />
        </td>
        <td>
            <input type="submit" value="Search" form="searchform" />
        </td>
    </tr>
    <tr>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.count).ToString() + @ShowButton("count", "count_desc"), "Index", new { sortOrder = ViewBag.countSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.date).ToString() + @ShowButton("date", "date"), "Index", new { sortOrder = ViewBag.dateSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.doctors.FIO).ToString() + " лікаря" + @ShowButton("docFIO", "docFIO_desc"), "Index", new { sortOrder = ViewBag.docFIOSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.storage.item_name).ToString() + @ShowButton("stItem_name", "stItem_name_desc"), "Index", new { sortOrder = ViewBag.stItem_nameSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.doctors.FIO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.storage.item_name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>