FirstTry/Controllers/PlacingInHospitalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FirstTry;
using FirstTry.Static;
using Microsoft.AspNet.Identity.Owin;

namespace FirstTry.Controllers
{
    public class PlacingInHospitalController : Controller
    {
        private polyclinicEntities db = new polyclinicEntities();

        // GET: PlacingInHospital
        public ActionResult Index(string sortOrder, string[] SearchStrings)
        {
            var placing_in_hospital = db.placing_in_hospital.Include(p => p.doctors).Include(p => p.patients).ToList();

            ViewBag.date_startSortParm = sortOrder == "date_start" ? "date_start_desc" : "date_start";
            ViewBag.date_endSortParm = sortOrder == "date_end" ? "date_end_desc" : "date_end";
            ViewBag.reasonSortParm = sortOrder == "reason" ? "reason_desc" : "reason";
            ViewBag.treatmentSortParm = sortOrder == "treatment" ? "treatment_desc" : "treatment";
            ViewBag.docFIOSortParm = sortOrder == "docFIO" ? "docFIO_desc" : "docFIO";
            ViewBag.patFIOSortParm = sortOrder == "patFIO" ? "patFIO_desc" : "patFIO";

            ViewData["sortOrder"] = sortOrder;

            if (SearchStrings != null && SearchStrings.Length == 1)
            {
                SearchStrings = SearchStrings[0].Split('%');
            }
            ViewBag.SearchStrings = SearchStrings;

            placing_in_hospital = SortData(sortOrder, placing_in_hospital);

            if (SearchStrings != null && SearchStrings.Length == 6)
                placing_in_hospital = SearchData(SearchStrings, placing_in_hospital);

            return View(placing_in_hospital);
        }

        public List<placing_in_hospital> SearchData(string[] SearchStrings, List<placing_in_hospital> placing_in_hospital)
        {
            if (!string.IsNullOrEmpty(SearchStrings[0]))
            {
                placing_in_hospital = placing_in_hospital.Where(s => s.date_start.ToString().Contains(SearchStrings[0])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[1]))
            {
                placing_in_hospital = placing_in_hospital.Where(s => s.date_end.ToString().Contains(SearchStrings[1])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[2]))
            {
                placing_in_hospital = placing_in_hospital.Where(s => s.reason.ToString().Contains(SearchStrings[2])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[3]))
            {
                placing_in_hospital = placing_in_hospital.Where(s => s.treatment.Contains(SearchStrings[3])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[3]))
            {
                placing_in_hospital = placing_in_hospital.Where(s => s.doctors.FIO.Contains(SearchStrings[3])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[3]))
            {
                placing_in_hospital = placing_in_hospital.Where(s => s.patients.FIO.Contains(SearchStrings[3])).ToList();
            }

            return placing_in_hospital;
        }

        public List<placing_in_hospital> SortData(string sortOrder, List<placing_in_hospital> placing_in_hospital)
        {
            switch (sortOrder)
            {
                case "date_start":
                    placing_in_hospital = placing_in_hospital.OrderBy(s => s.date_start).ToList();
                    break;
                case "date_start_desc":
                    placing_in_hospital = placing_in_hospital.OrderByDescending(s => s.date_start).ToList();
                    break;
                case "date_end":
                    placing_in_hospital = placing_in_hospital.OrderBy(s => s.date_end).ToList();
                    break;
                case "date_end_desc":
                    placing_in_hospital = placing_in_hospital.OrderByDescending(s => s.date_end).ToList();
                    break;
                case "reason":
                    placing_in_hospital = placing_in_hospital.OrderBy(s => s.reason).ToList();
                    break;
                case "reason_desc":
                    placing_in_hospital = placing_in_hospital.OrderByDescending(s => s.reason).ToList();
                    break;
                case "treatment":
                    placing_in_hospital = placing_in_hospital.OrderBy(s => s.treatment).ToList();
                    break;
                case "treatment_desc":
                    placing_in_hospital = placing_in_hospital.OrderByDescending(s => s.treatment).ToList();
                    break; 
                case "docFIO":
                    placing_in_hospital = placing_in_hospital.OrderBy(s => s.doctors.FIO).ToList();
                    break;
                case "docFIO_desc":
                    placing_in_hospital = placing_in_hospital.OrderByDescending(s => s.doctors.FIO).ToList();
                    break; 
                case "patFIO":
                    placing_in_hospital = placing_in_hospital.OrderBy(s => s.patients.FIO).ToList();
                    break;
                case "patFIO_desc":
                    placing_in_hospital = placing_in_hospital.OrderByDescending(s => s.patients.FIO).ToList();
                    break;
            }

            return placing_in_hospital;
        }

        // GET: PlacingInHospital/Details/5
        [Authorize(Roles = "manager")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            placing_in_hospital placing_in_hospital = db.placing_in_hospital.Find(id);
            if (placing_in_hospital == null)
            {
                return HttpNotFound();
            }
            return View(placing_in_hospital);
        }

        // GET: PlacingInHospital/Create
        [Authorize(Roles = "manager, doctor")]
        public ActionResult Create()
        {
            ViewBag.attending_doctor_id = new SelectList(db.doctors.Where((it) => it.date_end_work == null), "id", "FIO");
            ViewBag.patient_id = new SelectList(db.patients, "id", "FIO");

            placing_in_hospital placing_in_hospital = new placing_in_hospital();
            placing_in_hospital.date_start = DateTime.Now;

            return View(placing_in_hospital);
        }

        // POST: PlacingInHospital/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "manager, doctor")]
        public ActionResult Create([Bind(Include = "id,attending_doctor_id,patient_id,date_start,date_end,reason,treatment")] placing_in_hospital placing_in_hospital)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.placing_in_hospital.Add(placing_in_hospital);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    if (ex.InnerException != null && ex.InnerException.InnerException != null)
                    {
                        var mess = ex.InnerException.InnerException.Message;
                        ViewData["error"] = mess.Substring(0, mess.Length > 65 ? mess.Length - 65 : mess.Length);
                    }
                }
            }

            ViewBag.attending_doctor_id = new SelectList(db.doctors, "id", "FIO", placing_in_hospital.attending_doctor_id);
            ViewBag.patient_id = new SelectList(db.patients, "id", "FIO", placing_in_hospital.patient_id);
            return View(placing_in_hospital);
        }

        // GET: PlacingInHospital/Edit/5
        [Authorize(Roles = "manager, doctor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            placing_in_hospital placing_in_hospital = db.placing_in_hospital.Find(id);

            if (User.IsInRole("manager") || User.IsInRole("director")) ;
            else if (User.IsInRole("doctor"))
            {
                var user = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().Users.FirstOrDefault(it => it.UserName == User.Identity.Name);
                int doctorId = DoctorsId.getDoctorId(user.Id);
                if (doctorId != placing_in_hospital.attending_doctor_id)
                {
                    return RedirectToAction("Index");
                }
            }

            if (placing_in_hospital == null)
            {
                return HttpNotFound();
            }
            ViewBag.attending_doctor_id = new SelectList(db.doctors, "id", "FIO", placing_in_hospital.attending_doctor_id);
            ViewBag.patient_id = new SelectList(db.patients, "id", "FIO", placing_in_hospital.patient_id);
            return View(placing_in_hospital);
        }

        // POST: PlacingInHospital/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "manager, doctor")]
        public ActionResult Edit([Bind(Include = "id,attending_doctor_id,patient_id,date_start,date_end,reason,treatment")] placing_in_hospital placing_in_hospital)
        {
            if (User.IsInRole("manager") || User.IsInRole("director")) ;
            else if (User.IsInRole("doctor"))
            {

FirstTry/Views/PlacingInHospital/Create.cshtml
@model FirstTry.placing_in_hospital

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div class="alert-danger">
    @ViewData["error"]
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Створення</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.attending_doctor_id, "attending_doctor_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("attending_doctor_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.attending_doctor_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient_id, "patient_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("patient_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.patient_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_start, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_end, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_end, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_end, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reason, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reason, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.treatment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.treatment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.treatment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FirstTry/Views/PlacingInHospital/Delete.cshtml
@model FirstTry.placing_in_hospital

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Видалення</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.date_start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_start)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_end)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_end)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.treatment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.treatment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doctors.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctors.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.patients.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patients.FIO)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FirstTry/Views/PlacingInHospital/Details.cshtml
@model FirstTry.placing_in_hospital

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Перегляд</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.date_start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_start)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_end)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_end)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.treatment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.treatment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doctors.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctors.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.patients.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patients.FIO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FirstTry/Views/PlacingInHospital/Edit.cshtml
@model FirstTry.placing_in_hospital

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Редагування</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.attending_doctor_id, "attending_doctor_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("attending_doctor_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.attending_doctor_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient_id, "patient_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("patient_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.patient_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_start, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_end, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_end, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_end, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reason, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reason, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.treatment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.treatment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.treatment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FirstTry/Views/PlacingInHospital/Index.cshtml
@model IEnumerable<FirstTry.placing_in_hospital>

@{
    ViewBag.Title = "Index";
}

@{ string ShowButton(string up, string down)
    {
        if (ViewData["sortOrder"] != null)
        {

            if (ViewData["sortOrder"].ToString() == up)
            {
                return HttpUtility.HtmlEncode("↑");
            }
            else if (ViewData["sortOrder"].ToString() == down)
            {
                return HttpUtility.HtmlEncode("↓");
            }
        }
        return "";
    }
}

@{ string GetSearchString(int index)
    {
        if (ViewBag.SearchStrings != null)
        {
            return ViewBag.SearchStrings[index];
        }
        return string.Empty;
    }
}

@{ string GetAgregateSearchString()
    {
        if (ViewBag.SearchStrings != null)
        {
            return (ViewBag.SearchStrings as string[]).Aggregate((sum, next) => sum + '%' + next);
        }
        return string.Empty;
    }
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("", "PlacingInHospital", FormMethod.Get, new { id = "searchform" }))
{

}

<input type="text" name="sortOrder" form="searchform" value="@ViewData["sortOrder"]" class="hidden" />

<table class="table">
    <tr>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(0)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(1)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(2)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(3)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(4)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(5)" />
        </td>
        <td>
            <input type="submit" value="Search" form="searchform" />
        </td>
    </tr>
    <tr>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.date_start).ToString() + @ShowButton("date_start", "date_start_desc"), "Index", new { sortOrder = ViewBag.date_startSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.date_end).ToString() + @ShowButton("date_end", "date_end_desc"), "Index", new { sortOrder = ViewBag.date_endSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.reason).ToString() + @ShowButton("reason", "reason_desc"), "Index", new { sortOrder = ViewBag.reasonSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.treatment).ToString() + @ShowButton("treatment", "treatment_desc"), "Index", new { sortOrder = ViewBag.treatmentSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.doctors.FIO).ToString() + " лікаря" + @ShowButton("docFIO", "docFIO_desc"), "Index", new { sortOrder = ViewBag.docFIOSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.patients.FIO).ToString() + " пацієнта" + @ShowButton("patFIO", "patFIO_desc"), "Index", new { sortOrder = ViewBag.patFIOSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.date_start)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date_end)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.reason)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.treatment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.doctors.FIO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.patients.FIO)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>