FirstTry/Controllers/DoctorVisitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FirstTry;
using FirstTry.Static;
using Microsoft.AspNet.Identity.Owin;

namespace FirstTry.Controllers
{
    public class DoctorVisitsController : Controller
    {
        private polyclinicEntities db = new polyclinicEntities();

        // GET: DoctorVisits
        public ActionResult Index(string sortOrder, string[] SearchStrings)
        {
            ViewBag.dateSortParm = sortOrder == "date" ? "date_desc" : "date";
            ViewBag.reasonSortParm = sortOrder == "reason" ? "reason_desc" : "reason";
            ViewBag.resultSortParm = sortOrder == "result" ? "result_desc" : "result";
            ViewBag.treatmentSortParm = sortOrder == "treatment" ? "treatment_desc" : "treatment";
            ViewBag.docFIOSortParm = sortOrder == "docFIO" ? "docFIO_desc" : "docFIO";
            ViewBag.patFIOSortParm = sortOrder == "patFIO" ? "patFIO_desc" : "patFIO";

            ViewData["sortOrder"] = sortOrder;

            if (SearchStrings != null && SearchStrings.Length == 1)
            {
                SearchStrings = SearchStrings[0].Split('%');
            }
            ViewBag.SearchStrings = SearchStrings;

            var doctor_visits = db.doctor_visits.Include(d => d.doctors).Include(d => d.patients).ToList();

            doctor_visits = SortDoctorVisits(sortOrder, doctor_visits);

            if (SearchStrings != null && SearchStrings.Length == 6)
                doctor_visits = SearchDoctorVisits(SearchStrings, doctor_visits);

            return View(doctor_visits);
        }

        public List<doctor_visits> SearchDoctorVisits(string[] SearchStrings, List<doctor_visits> doctor_visits)
        {
            if (!string.IsNullOrEmpty(SearchStrings[0]))
            {
                doctor_visits = doctor_visits.Where(s => s.date.ToString().Contains(SearchStrings[0])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[1]))
            {
                doctor_visits = doctor_visits.Where(s => s.reason.Contains(SearchStrings[1])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[2]))
            {
                doctor_visits = doctor_visits.Where(s => s.result.Contains(SearchStrings[2])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[3]))
            {
                doctor_visits = doctor_visits.Where(s => s.treatment.Contains(SearchStrings[3])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[4]))
            {
                doctor_visits = doctor_visits.Where(s => s.doctors.FIO.Contains(SearchStrings[4])).ToList();
            }
            if (!string.IsNullOrEmpty(SearchStrings[5]))
            {
                doctor_visits = doctor_visits.Where(s => s.patients.FIO.Contains(SearchStrings[5])).ToList();
            }            

            return doctor_visits;
        }

        public List<doctor_visits> SortDoctorVisits(string sortOrder, List<doctor_visits> doctor_visits)
        {
            switch (sortOrder)
            {
                case "date":
                    doctor_visits = doctor_visits.OrderBy(s => s.date).ToList();
                    break;
                case "date_desc":
                    doctor_visits = doctor_visits.OrderByDescending(s => s.date).ToList();
                    break;
                case "reason":
                    doctor_visits = doctor_visits.OrderBy(s => s.reason).ToList();
                    break;
                case "reason_desc":
                    doctor_visits = doctor_visits.OrderByDescending(s => s.reason).ToList();
                    break;
                case "result":
                    doctor_visits = doctor_visits.OrderBy(s => s.result).ToList();
                    break;
                case "result_desc":
                    doctor_visits = doctor_visits.OrderByDescending(s => s.result).ToList();
                    break;
                case "treatment":
                    doctor_visits = doctor_visits.OrderBy(s => s.treatment).ToList();
                    break;
                case "treatment_desc":
                    doctor_visits = doctor_visits.OrderByDescending(s => s.treatment).ToList();
                    break;
                case "docFIO":
                    doctor_visits = doctor_visits.OrderBy(s => s.doctors.FIO).ToList();
                    break;
                case "docFIO_desc":
                    doctor_visits = doctor_visits.OrderByDescending(s => s.doctors.FIO).ToList();
                    break;
                case "patFIO":
                    doctor_visits = doctor_visits.OrderBy(s => s.patients.FIO).ToList();
                    break;
                case "patFIO_desc":
                    doctor_visits = doctor_visits.OrderByDescending(s => s.patients.FIO).ToList();
                    break;                
            }

            return doctor_visits;
        }

        // GET: DoctorVisits/Details/5
        [Authorize(Roles = "manager")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor_visits doctor_visits = db.doctor_visits.Find(id);
            if (doctor_visits == null)
            {
                return HttpNotFound();
            }
            return View(doctor_visits);
        }

        // GET: DoctorVisits/Create
        [Authorize(Roles = "manager")]
        public ActionResult Create()
        {
            ViewBag.doctor_id = new SelectList(db.doctors.Where((it) => it.date_end_work == null), "id", "FIO");
            ViewBag.patient_id = new SelectList(db.patients, "id", "FIO");

            doctor_visits doctor_visits = new doctor_visits();
            doctor_visits.date = DateTime.Now;

            return View();
        }

        // POST: DoctorVisits/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "manager")]
        public ActionResult Create([Bind(Include = "id,doctor_id,patient_id,date,reason,result,treatment")] doctor_visits doctor_visits)
        {
            if (ModelState.IsValid)
            {
                db.doctor_visits.Add(doctor_visits);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.doctor_id = new SelectList(db.doctors, "id", "FIO", doctor_visits.doctor_id);
            ViewBag.patient_id = new SelectList(db.patients, "id", "FIO", doctor_visits.patient_id);
            return View(doctor_visits);
        }

        // GET: DoctorVisits/Edit/5
        [Authorize(Roles = "manager, doctor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor_visits doctor_visits = db.doctor_visits.Find(id);

            if (User.IsInRole("manager") || User.IsInRole("director")) ;
            else if (User.IsInRole("doctor"))
            {
                var user = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().Users.FirstOrDefault(it => it.UserName == User.Identity.Name);
                int doctorId = DoctorsId.getDoctorId(user.Id);
                if (doctorId != doctor_visits.doctor_id)
                {
                    return RedirectToAction("Index");
                }
            }
            
            if (doctor_visits == null)
            {
                return HttpNotFound();
            }
            ViewBag.doctor_id = new SelectList(db.doctors, "id", "FIO", doctor_visits.doctor_id);
            ViewBag.patient_id = new SelectList(db.patients, "id", "FIO", doctor_visits.patient_id);
            return View(doctor_visits);
        }

        // POST: DoctorVisits/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "manager, doctor")]
        public ActionResult Edit([Bind(Include = "id,doctor_id,patient_id,date,reason,result,treatment")] doctor_visits doctor_visits)
        {
            if (User.IsInRole("manager") || User.IsInRole("director")) ;
            else if (User.IsInRole("doctor"))
            {
                var user = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().Users.FirstOrDefault(it => it.UserName == User.Identity.Name);
                int doctorId = DoctorsId.getDoctorId(user.Id);
                if (doctorId != doctor_visits.doctor_id)
                {
                    return RedirectToAction("Index");
                }
            }

            if (ModelState.IsValid)
            {
                db.Entry(doctor_visits).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.doctor_id = new SelectList(db.doctors, "id", "FIO", doctor_visits.doctor_id);
            ViewBag.patient_id = new SelectList(db.patients, "id", "FIO", doctor_visits.patient_id);
            return View(doctor_visits);
        }

        // GET: DoctorVisits/Delete/5
        [Authorize(Roles = "manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

FirstTry/Views/DoctorVisits/Create.cshtml
@model FirstTry.doctor_visits

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Створення</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.doctor_id, "doctor_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("doctor_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.doctor_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient_id, "patient_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("patient_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.patient_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, "Дата", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reason, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reason, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.result, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.result, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.result, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.treatment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.treatment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.treatment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FirstTry/Views/DoctorVisits/Delete.cshtml
@model FirstTry.doctor_visits

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Видалення</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.result)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.result)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.treatment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.treatment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doctors.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctors.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.patients.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patients.FIO)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FirstTry/Views/DoctorVisits/Details.cshtml
@model FirstTry.doctor_visits

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Перегляд</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.result)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.result)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.treatment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.treatment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doctors.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctors.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.patients.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patients.FIO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FirstTry/Views/DoctorVisits/Edit.cshtml
@model FirstTry.doctor_visits

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Редагування</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.doctor_id, "doctor_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("doctor_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.doctor_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient_id, "patient_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("patient_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.patient_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reason, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reason, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.result, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.result, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.result, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.treatment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.treatment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.treatment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FirstTry/Views/DoctorVisits/Index.cshtml
@model IEnumerable<FirstTry.doctor_visits>

@{
    ViewBag.Title = "Index";
}

@{ string ShowButton(string up, string down)
    {
        if (ViewData["sortOrder"] != null)
        {

            if (ViewData["sortOrder"].ToString() == up)
            {
                return HttpUtility.HtmlEncode("↑");
            }
            else if (ViewData["sortOrder"].ToString() == down)
            {
                return HttpUtility.HtmlEncode("↓");
            }
        }
        return "";
    }
}

@{ string GetSearchString(int index)
    {
        if (ViewBag.SearchStrings != null)
        {
            return ViewBag.SearchStrings[index];
        }
        return string.Empty;
    }
}

@{ string GetAgregateSearchString()
    {
        if (ViewBag.SearchStrings != null)
        {
            return (ViewBag.SearchStrings as string[]).Aggregate((sum, next) => sum + '%' + next);
        }
        return string.Empty;
    }
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("", "DoctorVisits", FormMethod.Get, new { id = "searchform" }))
{

}

<input type="text" name="sortOrder" form="searchform" value="@ViewData["sortOrder"]" class="hidden" />

<table class="table">
    <tr>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(0)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(1)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(2)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(3)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(4)" />
        </td>
        <td>
            <input type="text" name="SearchStrings" form="searchform" style="width: 100%" value="@GetSearchString(5)" />
        </td>        
        <td>
            <input type="submit" value="Search" form="searchform" />
        </td>
    </tr>
    <tr>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.date).ToString() + @ShowButton("date", "date_desc"), "Index", new { sortOrder = ViewBag.dateSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.reason).ToString() + @ShowButton("reason", "reason_desc"), "Index", new { sortOrder = ViewBag.reasonSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.result).ToString() + @ShowButton("result", "result_desc"), "Index", new { sortOrder = ViewBag.resultSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.treatment).ToString() + @ShowButton("treatment", "treatment_desc"), "Index", new { sortOrder = ViewBag.treatmentSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.doctors.FIO).ToString() + " лікаря" + @ShowButton("docFIO", "docFIO_desc"), "Index", new { sortOrder = ViewBag.docFIOSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th>
            @Html.ActionLink(@Html.DisplayNameFor(model => model.patients.FIO).ToString() + " паціента" + @ShowButton("patFIO", "patFIO_desc"), "Index", new { sortOrder = ViewBag.patFIOSortParm, SearchStrings = GetAgregateSearchString() })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.reason)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.result)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.treatment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.doctors.FIO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.patients.FIO)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>